# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f78e101d582bac11b43e348c61a67e7ee80e3229870c9c34b4f03c255a701743f1a1391d4fada2a3256e0b32e319d38b43d2937cc32e7edd6eae68810fd8926

test:
  secret_key_base: 0ba9e33fda0c2dfc66d177ab9c85cfbb236086510527c4af6c7cad529846f3ae2dd9ef6b03efddad160263230fa14f3c825e31bcd2bc9fa15c2a68003b0f7613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
